version: "3.3"

services:


  greeter:
    build:
      context: .
    image: AddWallet
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - nats
      - redis
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal


networks:
  internal:

volumes:
  data:
